######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 14 15:01:18 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cc
